Use komega in suite tests
onmetal/cloud-provider-onmetal pull request #210
Opened 2023-05-09 06:11 UTC by ushabelgur

# Proposed Changes
- Use komega in tests-

Fixes #208

2023-05-09 06:33 UTC, afritzler requested changes
Thanks a lot for you PR. Please have a look at my comments.

2023-05-09 06:33 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> +		Eventually(instanceMetadata).Should(SatisfyAll(HaveField("ProviderID", fmt.Sprintf("%s://%s/%s", ProviderName, machine.Namespace, machine.Name)),
Can you put the `HaveField` on a new line and factor out the `fmt.Sprintf` into a helper method.

2023-05-09 06:33 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> +			)), HaveField("Zone", "zone1"), HaveField("Region", "")))
Put each `HaveField` on a new line for better readability please.

2023-05-09 06:33 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +		lbObject := &networkingv1alpha1.LoadBalancer{ObjectMeta: metav1.ObjectMeta{Name: lbName, Namespace: service.Namespace}}
You can reuse the `lb` object defined in L209.

2023-05-09 06:33 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +			})), HaveField("Destinations", items)))
I would not collect the `items` above. Instead directly use an array here as we know how the `items` should look like. Please avoid if statements in test cases as there should be no conditioned execution in unit/suite tests.

2023-05-09 06:33 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +		lbRouting = &networkingv1alpha1.LoadBalancerRouting{ObjectMeta: metav1.ObjectMeta{Namespace: service.Namespace, Name: lbName}}
Please use the routing object defined above here.

2023-05-09 06:33 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +			HaveField("Destinations", items)))
Here again ensure on a concrete array which you define.

2023-05-09 06:33 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +		for _, ingress := range ingresses {
Instead of using a for loop use a `ContainsElements` on the `Ingress` array in the status.

2023-05-09 09:54 UTC, ushabelgur commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> +			)), HaveField("Zone", "zone1"), HaveField("Region", "")))
Done

2023-05-09 09:54 UTC, ushabelgur commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +			})), HaveField("Destinations", items)))
Done

2023-05-09 09:54 UTC, ushabelgur commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +		lbRouting = &networkingv1alpha1.LoadBalancerRouting{ObjectMeta: metav1.ObjectMeta{Namespace: service.Namespace, Name: lbName}}
Done

2023-05-09 09:55 UTC, ushabelgur commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +		for _, ingress := range ingresses {
Modified test accordingly

2023-05-09 09:55 UTC, ushabelgur commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +			HaveField("Destinations", items)))
done

2023-05-11 14:49 UTC, afritzler requested changes

2023-05-11 14:49 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +		lbRouting = &networkingv1alpha1.LoadBalancerRouting{ObjectMeta: metav1.ObjectMeta{Namespace: service.Namespace, Name: lbName}}
Please remove this `lbRouting` and use the one defined in L271.

2023-05-12 07:25 UTC, afritzler approved these changes

2023-05-12 07:25 UTC, merged