Create LoadBalancer instance even if no Nodes are available
onmetal/cloud-provider-onmetal pull request #227
Opened 2023-06-04 18:16 UTC by Ashughorla

# Proposed Changes

- Change condition of creating LB instance 
- Test case

Fixes https://github.com/onmetal/cloud-provider-onmetal/issues/224

2023-06-05 05:39 UTC, afritzler requested changes

2023-06-05 05:39 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer_test.go
>  		By("expecting an error if there are no nodes available")
Can you please adjust the description here

2023-06-05 05:45 UTC, Ashughorla commented on pkg/cloudprovider/onmetal/load_balancer_test.go
>  		By("expecting an error if there are no nodes available")
Yes sure. Addressed.

2023-06-05 05:55 UTC, afritzler commented
I am actually not sure if we really need the check for the `ClusterIP` type as this is checked here: https://github.com/kubernetes/cloud-provider/blob/master/controllers/service/controller.go#L369

2023-06-05 09:21 UTC, Ashughorla commented
@afritzler Updated the changes. Please have a look.

2023-06-05 09:25 UTC, afritzler approved these changes

2023-06-06 07:39 UTC, afritzler approved these changes

2023-06-06 07:39 UTC, merged