Implement  Routing Controller in cloud provider
onmetal/cloud-provider-onmetal pull request #241
Opened 2023-06-29 14:22 UTC by kasabe28

# Proposed Changes

- Add Routing Controller
- Write testcases for Routing Controller

Fixes #240

2023-06-30 07:58 UTC, afritzler requested changes

2023-06-30 07:58 UTC, afritzler commented on pkg/cloudprovider/onmetal/cloud.go
> +		log.Fatalf("Failed to setup field indexe for network interfacer: %v", err)
```suggestion
		log.Fatalf("Failed to setup field indexer for network interface: %v", err)
```

2023-06-30 07:58 UTC, afritzler commented on pkg/cloudprovider/onmetal/cloud_test.go
> -		Expect(ok).To(BeFalse())
How about using `BeTrue()` here.

2023-06-30 07:58 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +	err := o.onmetalClient.List(ctx, nics, client.InNamespace(o.onmetalNamespace), client.MatchingFields{
What if I have a `Machine` which is not part of the cluster but is in the same `Network`? Its `NetworkInterface` will have the correct `networkRef`.

2023-06-30 07:58 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +							nic.Spec.Prefixes = nic.Spec.Prefixes[:i+copy(nic.Spec.Prefixes[i:], nic.Spec.Prefixes[i+1:])]
Wouldn't this be a better way to update the `Prefix` list: ```    mySlice = append(mySlice[:index], mySlice[index+1:]...)``` where `index` is the index of the `Prefix` which should be removed.

2023-06-30 08:58 UTC, kasabe28 commented on pkg/cloudprovider/onmetal/cloud_test.go
> -		Expect(ok).To(BeFalse())
Its removed from here, because its been covered here: https://github.com/onmetal/cloud-provider-onmetal/blob/feature-cloud-routes/pkg/cloudprovider/onmetal/routes_test.go#L117

2023-07-06 13:13 UTC, kasabe28 commented on pkg/cloudprovider/onmetal/routes.go
> +	err := o.onmetalClient.List(ctx, nics, client.InNamespace(o.onmetalNamespace), client.MatchingFields{
Added cluster name to Machine and Network Interface. Now Network Interfaces will be filtered with cluster name label along with network filter.

2023-07-10 08:03 UTC, afritzler commented on pkg/cloudprovider/onmetal/constants.go
> +	LabelClusterNameKey = "kubernetes.io/cluster"
```suggestion
	LabeKeylClusterName = "kubernetes.io/cluster"
```

2023-07-10 08:08 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2.go
> +	klog.V(2).InfoS("Updating Machine by adding cluster name label", "Machine", client.ObjectKeyFromObject(machine), "Node", node)
```suggestion
	klog.V(2).InfoS("Adding cluster name label to Machine object", "Machine", client.ObjectKeyFromObject(machine), "Node", node.Name)
```

2023-07-10 08:08 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2.go
> +		return nil, fmt.Errorf("failed to patch Machine %s for Node %s: %w", client.ObjectKeyFromObject(machine), node, err)
```suggestion
		return nil, fmt.Errorf("failed to patch Machine %s for Node %s: %w", client.ObjectKeyFromObject(machine), node.Name, err)
```

2023-07-10 08:11 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2.go
> +		klog.V(2).InfoS("Updating NetworkInterface by adding cluster name label", "NetworkInterface", client.ObjectKeyFromObject(nic), "Node", node, "Label", nic.Labels[LabelClusterNameKey])
```suggestion
		klog.V(2).InfoS("Adding cluster name label to NetworkInterface", "NetworkInterface", client.ObjectKeyFromObject(nic), "Node", node.Name, "Label", nic.Labels[LabelClusterNameKey])
```

2023-07-10 08:12 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2.go
> +			return nil, fmt.Errorf("failed to patch NetworkInterface %s for Node %s: %w", client.ObjectKeyFromObject(nic), node, err)
```suggestion
			return nil, fmt.Errorf("failed to patch NetworkInterface %s for Node %s: %w", client.ObjectKeyFromObject(nic), node.Name, err)
```

2023-07-10 08:15 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> -				GenerateName: "machine-",
Why not using the `GeneratedName` here?

2023-07-10 08:15 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> +								Name: "machine1-my-nic",
You can reference the `machine.Name` here if you are using `GeneratedName` above.

2023-07-10 08:16 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> +				Name:      "machine1-my-nic",
The name of the `NetworkInterface` must be constructed using `fmt.Sprintf` when using `GeneratedName` above.

2023-07-10 08:18 UTC, afritzler commented on pkg/cloudprovider/onmetal/suite_test.go
> +		cloudConfig := CloudConfig{NetworkName: network.Name, PrefixName: prefix.Name, ClusterName: "test"}
As the cluster name is part of the cloud config setup I would return this as part of the `SetupTest` method.

2023-07-10 08:18 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes_test.go
> +	const clusterName = "test"
As mentioned in the `suite_test.go` comments, I would return the cluster name in the `SetupTest` method.

2023-07-10 08:20 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes_test.go
> +
I would also add a test here with a `Machine` and `NetworkInterface` in the same `Network` which does not have this label and ensure that the `Routes` list is still the same.

2023-07-10 08:22 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +	klog.V(2).InfoS("List Routes", "Cluster", clusterName, "Network", o.cloudConfig.NetworkName)
No need to print out the `Network` here as this is not passed to the method via an arg.

2023-07-10 08:22 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +	err := o.onmetalClient.List(ctx, nics, client.InNamespace(o.onmetalNamespace), client.MatchingFields{
Use a single line `if err := ....; err != nil { ...` here.

2023-07-10 08:25 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +	// iterate over all network interfaces and create a route for each prefix
We are technically not "creating" a route for each prefix here. Instead we are collecting all the `Prefixes` as routes.

2023-07-10 08:34 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +	node := string(route.TargetNode)
Please use `nodeName` here as a variable name.

2023-07-10 08:35 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +	klog.V(2).InfoS("Create Route", "Cluster", clusterName, "Route", route, "NameHint", nameHint)
```suggestion
	klog.V(2).InfoS("Creating Route", "Cluster", clusterName, "Route", route, "NameHint", nameHint)
```

2023-07-10 08:36 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +
Add a log output here: something a long the line of "Created Route ...."

2023-07-10 08:38 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +					err := o.onmetalClient.Get(ctx, client.ObjectKey{Namespace: o.onmetalNamespace, Name: networkInterfaceName}, nic)
Please use a single line `if err := ...` here

2023-07-10 08:39 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +						klog.V(2).InfoS("Updating NetworkInterface by adding prefix", "NetworkInterface", client.ObjectKeyFromObject(nic), "Node", node, "Prefix", route.DestinationCIDR)
```suggestion
						klog.V(2).InfoS("Updating NetworkInterface by adding prefix", "NetworkInterface", client.ObjectKeyFromObject(nic), "Node", node.Name, "Prefix", route.DestinationCIDR)
```

2023-07-10 08:39 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +							return fmt.Errorf("failed to patch NetworkInterface %s for Node %s: %w", client.ObjectKeyFromObject(nic), node, err)
```suggestion
							return fmt.Errorf("failed to patch NetworkInterface %s for Node %s: %w", client.ObjectKeyFromObject(nic), node.Name, err)
```

2023-07-10 08:39 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +						klog.V(2).InfoS("NetworkInterface prefix already exists", "NetworkInterface", client.ObjectKeyFromObject(nic), "Node", node, "Prefix", route.DestinationCIDR)
```suggestion
						klog.V(2).InfoS("NetworkInterface prefix already exists", "NetworkInterface", client.ObjectKeyFromObject(nic), "Node", node.Name, "Prefix", route.DestinationCIDR)
```

2023-07-10 08:39 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +	klog.V(2).InfoS("Delete Route", "Cluster", clusterName, "Route", route)
```suggestion
	klog.V(2).InfoS("Deleting Route", "Cluster", clusterName, "Route", route)
```

2023-07-10 08:40 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +
Add a log output here: something like "Deleted Route ..."

2023-07-10 08:40 UTC, afritzler commented on pkg/cloudprovider/onmetal/routes.go
> +					err := o.onmetalClient.Get(ctx, client.ObjectKey{Namespace: o.onmetalNamespace, Name: networkInterfaceName}, nic)
Use a single line `if err := ...`

2023-07-11 08:32 UTC, afritzler requested changes

2023-07-11 08:32 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> +		machine.Spec.NetworkInterfaces[0].NetworkInterfaceSource = computev1alpha1.NetworkInterfaceSource{
I would have moved this part down after the `NetworkInterface` has been created and the patch the `Machine` object with the correct NIC ref.

2023-07-11 08:32 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> +	ns, _, network, _ := SetupTest()
You want to store the `clusterName` here.

2023-07-11 08:32 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> +			HaveField("Labels", map[string]string{LabeKeylClusterName: "test"}),
Use the `clusterName` from the `SetupTest` call here.

2023-07-11 08:32 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> +			HaveField("Labels", map[string]string{LabeKeylClusterName: "test"}),
Use the `clusterName` from the `SetupTest` call here.

2023-07-12 11:52 UTC, afritzler requested changes

2023-07-12 11:52 UTC, afritzler commented on pkg/cloudprovider/onmetal/instances_v2_test.go
> +		machine.Spec.NetworkInterfaces[0].NetworkInterfaceSource = computev1alpha1.NetworkInterfaceSource{
Down below you are patching only the `Status` subresource. You also want to patch the `Machine` object iself.

2023-07-12 13:31 UTC, afritzler approved these changes

2023-07-12 13:31 UTC, merged