Extend Testing of Routes Controller Methods for Machine Network Interfaces
onmetal/cloud-provider-onmetal pull request #254
Opened 2023-07-27 11:02 UTC by sujeet01

- Extend routes tests to handle `Machine` instances that reference both ephemeral and static `NetworkInterface` instances Fixes #252
- Fix typos

2023-07-28 11:10 UTC, Rohit-0505 requested changes

2023-07-28 11:10 UTC, Rohit-0505 commented on pkg/cloudprovider/onmetal/routes_test.go
>  			ObjectMeta: metav1.ObjectMeta{
@sujeet01 Can we move the machine and node object creation in `BeforeEach` block to avoid the repetition?

2023-07-28 11:54 UTC, sujeet01 commented on pkg/cloudprovider/onmetal/routes_test.go
>  			ObjectMeta: metav1.ObjectMeta{
Done.

2023-08-01 10:19 UTC, sujeet01 commented
@afritzler Could you please have a look and let me know if you have any suggestions.

2023-08-03 07:14 UTC, afritzler approved these changes

2023-08-03 07:15 UTC, merged