Handle type switching of LoadBalancer from Internal to Public and vice versa
onmetal/cloud-provider-onmetal pull request #272
Opened 2023-08-24 07:13 UTC by kasabe28

# Proposed Changes

- Update load balancer controller to wait until LoadBalancerStatus is updated with valid IP, when load balancer type is switched Fixes #269 
- Modify testcase for load balancer

2023-08-25 11:55 UTC, afritzler requested changes

2023-08-25 11:55 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer.go
> +		if existingLoadBalancerType != desiredLoadBalancerType {
You can do the check for the existing type directly in the if statement. There is no need to assign this to a variable.

2023-08-25 11:55 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer.go
> +	if err := o.onmetalClient.Get(ctx, client.ObjectKey{Namespace: o.onmetalNamespace, Name: loadBalancerName}, existingLoadBalancer); err == nil {
You also need to handle the error case here: e.g. what happens when there is an error getting the LB resource. One error could be NotFound and the other one could be some communication/RBAC etc issue.

2023-08-25 11:55 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer.go
> +func waitLoadBalancerActive(ctx context.Context, existingLoadBalancerType networkingv1alpha1.LoadBalancerType, service *v1.Service,
Can we move the client as the second parameter of the method.

2023-08-25 11:55 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer.go
> +		err := onmetalClient.Get(ctx, client.ObjectKey{Namespace: loadBalancer.Namespace, Name: loadBalancer.Name}, loadBalancer)
Can we use a single line `if err := ...` here.

2023-08-25 11:55 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer.go
> +		return loadBalancerStatus, fmt.Errorf("timeout waiting for the onmetal LoadBalancer %s to become ready", client.ObjectKeyFromObject(loadBalancer))
```suggestion
		return loadBalancerStatus, fmt.Errorf("timeout waiting for the LoadBalancer %s to become ready", client.ObjectKeyFromObject(loadBalancer))
```

2023-08-25 11:55 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer.go
> +	klog.V(2).InfoS("Waiting for onmetal LoadBalancer to be deleted", "LoadBalancer", client.ObjectKeyFromObject(loadBalancer))
```suggestion
	klog.V(2).InfoS("Waiting for LoadBalancer instance to be deleted", "LoadBalancer", client.ObjectKeyFromObject(loadBalancer))
```

2023-08-25 11:55 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer.go
> +	klog.V(2).InfoS("Deleted onmetal LoadBalancer", "LoadBalancer", client.ObjectKeyFromObject(loadBalancer))
```suggestion
	klog.V(2).InfoS("Deleted LoadBalancer", "LoadBalancer", client.ObjectKeyFromObject(loadBalancer))
```

2023-08-25 11:55 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> -		By("patching internal IP in load balancer status")
Is there a reason why the `By` statement has been removed?

2023-08-25 11:55 UTC, afritzler commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> -		By("patching internal IP in load balancer status")
Same as above.

2023-08-28 07:24 UTC, kasabe28 commented on pkg/cloudprovider/onmetal/load_balancer.go
> +		if existingLoadBalancerType != desiredLoadBalancerType {
`existingLoadBalancerType` is being passed to `waitLoadBalancerActive`, so variable is needed here.

2023-08-28 09:18 UTC, kasabe28 commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> -		By("patching internal IP in load balancer status")
It is moved to line 270

2023-08-28 09:19 UTC, kasabe28 commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> -		By("patching internal IP in load balancer status")
Moved to line 451

2023-08-28 13:22 UTC, afritzler approved these changes

2023-08-28 13:22 UTC, merged