Use goroutines to patch `LoadBalancer` status in tests
onmetal/cloud-provider-onmetal pull request #308
Opened 2023-10-16 08:20 UTC by kasabe28

# Proposed Changes

- Patch `LoadBalancer` status using goroutines in tests Fixes #304 
- Update Makefile to cleanup go.sum file after test

2023-10-25 08:15 UTC, afritzler requested changes

2023-10-25 08:15 UTC, afritzler commented on Makefile
> +	go mod tidy
We don't want to have a tidy call in the `Makefile` as this is typically is caused by the local dev setup.

2023-10-25 09:14 UTC, kasabe28 commented on pkg/cloudprovider/onmetal/load_balancer_test.go
> +			By("patching public IP into load balancer status")
Done

2023-10-25 09:14 UTC, kasabe28 commented on Makefile
> +	go mod tidy
Ok. Done.

2023-10-26 10:24 UTC, afritzler approved these changes

2023-10-26 10:24 UTC, merged